src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java
Adding locations of "coverage.xml" files to sourcePaths in case of current directory (".") specified as root directory.
FIXES https://issues.jenkins-ci.org/browse/JENKINS-13889
=> [FIXED JENKINS-13889] Not able to find source code from subdirectories

.gitignore, src/main/java/hudson/plugins/cobertura/BuildUtils.java, src/main/java/hudson/plugins/cobertura/CoberturaBuildAction.java, src/main/java/hudson/plugins/cobertura/CoberturaProjectAction.java, src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java, src/main/java/hudson/plugins/cobertura/targets/CoverageResult.java, src/main/resources/hudson/plugins/cobertura/CoberturaPublisher/config.properties, src/test/java/hudson/plugins/cobertura/CoverageResultBuilder.java
If a previous build is still running, it will be ignored (along with
any earlier builds).
=> [JENKINS-26823] Prevent concurrent builds blocking

src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java
This method seems to be unused.
=> Remove unused method: CoberturaPublisher.getCoberturaReportDir

README.md
change the link of Cobertura from sourceforge.net to github.com
=> change the link of Cobertura

pom.xml
Given the discussion in <https://groups.google.com/forum/#!topic/jenkinsci-dev/J--7iWOEb00> and the change accepted in <https://github.com/jenkins-infra/repository-permissions-updater/pull/260>, this PR updates the list of maintainers within the plugin and published on the Jenkins Wiki.
=> Update list of maintainers

src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java, src/main/java/hudson/plugins/cobertura/targets/CoverageTarget.java
I have created a branch that implements pipeline support, and the very basic thing worked in my own deployment (ran a single build with the CoberturaPublisher step). It ran with the following entry in my Jenkinsfile:
```
step([$class: 'CoberturaPublisher', autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'coverage.xml', failNoReports: false, failUnhealthy: false, failUnstable: false, maxNumberOfBuilds: 0, onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false])
```
Since I'm not completely familiar with the Jenkins API, there are probably bugs and regressions, but I did get a report and a graph at the top of my multibranch build after running a job on a separate build slave. More eyes to look at this are appreciated. Here's what I'm unsure about:
- I …
=> JENKINS-30700 / #50 Jenkins pipeline support

src/main/java/hudson/plugins/cobertura/targets/CoverageResult.java
<https://issues.jenkins-ci.org/browse/JENKINS-6425> Supersedes #56.
=> JENKINS-6425 Avoid EnumSet.copyOf of empty sets

src/main/java/hudson/plugins/cobertura/CoberturaBuildAction.java, src/main/java/hudson/plugins/cobertura/targets/CoverageResult.java
This PR resolves JENKINS-17800 by removing use of the deprecated ChartUtil class, instead using the hudson.utils.Graph class directly, substituting with code similar to the deprecation replacement at https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/util/ChartUtil.java#L143
Since https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/util/Graph.java#L117 contains the timestamp check already, we pass the timestamp directly to the Graph constructor.
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/util/Graph.java#L157 shows that the new Graph class already contains an equivalent check to what https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/util/ChartUtil.java#L260 is doing to populate …
=> JENKINS-17800 remove deprecated use of ChartUtil.generateGraph

src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java, src/test/java/hudson/plugins/cobertura/CoberturaPublisherPipelineTest.java
This addresses issue #59 
> The Consider only stable builds option says - *Include only stable builds, i.e. exclude unstable and > failed ones. *
>
> But when the job actually fails, Cobertura prints "Skipping Cobertura coverage report as build was not UNSTABLE or better ..." and quits.
This change set the threshold to FAILURE or better when the flag is set, to match option text.
=> Publish report for failed jobs if onlyStable is false

pom.xml, src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java, src/test/java/hudson/plugins/cobertura/CoberturaPublisherPipelineTest.java
Addresses #67 by exposing coverage target for pipeline builds. For example, to set line coverage targets:
```
step([$class: 'CoberturaPublisher',
coberturaReportFile: '**/coverage.xml',
failUnhealthy: true,
failUnstable: true,
lineCoverageTargets: '90.0, 80.1, 50'])
```
The meaning of each number in the lineCoverageTargets is the same as available in the non-pipeline UI, in this case:
* Report health as 100% if line coverage > 90%
* Report health as 0% if line coverage < 80.1%
* Mark build as unstable if line coverage < 50%
In addition to lineCoverageTargets, you can specify the following properties:
* packageCoverageTargets
* fileCoverageTargets
* classCoverageTargets
* methodCoverageTargets
* conditionalCoverageTargets
=> Expose coverage targets

src/main/java/hudson/plugins/cobertura/renderers/SourceCodePainter.java, src/main/java/hudson/plugins/cobertura/targets/CoveragePaint.java, src/test/java/hudson/plugins/cobertura/targets/CoveragePaintTest.java
As Jenkins Pipeline scripts are becoming more prevalent, programmatic usage of plugin results will become more common. In this case, the result of the Cobertura plugin invocation in the pipeline can be used to feed other plugins, or published to code review systems. In support of such ends, `CoveragePaint` was missing a bit of information: The total number of lines in the file, including non-executable lines. Absent this, our code is having to re-open and re-read every line of every source file which the `SourceCodePainter` has already opened and read, just to count the total number of lines to send to our code review system along with the coverage paint information. This simple change eliminates the duplicate file reading and makes the Cobertura results more usable in a programmatic way. …
=> Add total line count to coverage paint for programmatic usage

src/main/java/hudson/plugins/cobertura/CoberturaAbortException.java, src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java, src/test/java/hudson/plugins/cobertura/CoberturaPublisherPipelineTest.java
Make sure all logs (including AbortException) contain the [Cobertura] prefix. This just extends what we were already doing, and adds some helper functions to make it more likely copy/pasted code will do this as well: Example output:
```[Cobertura] Publishing Cobertura coverage report...
[Cobertura] Publishing Cobertura coverage results...
[Cobertura] Cobertura coverage report found.
[Cobertura] Unhealthy for the following metrics:
Lines's health is 90.0 and set minimum health is 99.0.
Conditionals's health is 75.0 and set minimum health is 99.0.
...
ERROR: [Cobertura] Failing build because it is unhealthy.
Finished: FAILURE```
This addresses JENKINS-25781
=> JENKINS-25781 Add common prefix to all logs

pom.xml, src/main/java/hudson/plugins/cobertura/CoberturaAbortException.java, src/main/java/hudson/plugins/cobertura/CoberturaBuildAction.java, src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java, src/main/resources/hudson/plugins/cobertura/CoberturaBuildAction/summary.jelly
This addresses [JENKINS-47639] by saving the reason for failing a build in the build action, and showing it in the UI for the build.
=> JENKINS-47639 Display a message when missing coverage fails build

src/main/webapp/css/style.css
This fixes JENKINS-13489 with a slightly different approach then the patch in the ticket, making the CSS a bit less redundant.
PS: On some displays, #ffd is quite hard to differenciate from white, wouldn't something like #ffa work better?
=> [JENKINS-13489] Fix highlight for partially covered branches.

.gitignore, pom.xml, src/main/java/hudson/plugins/cobertura/MavenCoberturaPublisher.java, src/test/java/hudson/plugins/cobertura/CoberturaCoverageParserTest.java
Adds an explicit, optional dependency for the maven plugin to get rid of load warnings. JENKINS-44200
=> JENKINS-44200: Make maven plugin optional

src/main/java/hudson/plugins/cobertura/CoverageColumn.java
Avoid noisy NullPointerException in Jenkins log when lastResult does not contain the expected data.
=> Fix java.lang.NullPointerException when lastBuild does not contain coverage data for Line or Branch

pom.xml, src/main/resources/hudson/plugins/cobertura/adapter/cobertura-to-standard.xsl, src/test/java/hudson/plugins/cobertura/adapter/CoberturaReportAdapterTest.java, src/test/resources/hudson/plugins/cobertura/adapter/coberturaWithTheSameFileInDifferentPackages.xml
Hello.
There is a tool called Coverlet which is a .NET utility that collects
code coverage information and it produces reports in Cobertura. And this
Coberura report may contain one file in different packages
(.NET assemblies). .NET allows you to reference one file in multiple
projects(assemblies). Because of this, when you use the Cobertura plugin
to publish your code coverage in Jenkins it shows it incorrect because
the plugin uses Muenchian grouping which doesn't allow you to have
one file in multiple packages, it just groups them, globally for a whole
report. Changed the xslt scheme to use the for-each-group which allows
to have one file in multiple packages.
Thank you.
=> Support cases when one file may be in multiple packages

README.md, pom.xml
Hello 👋 
This PR introduces the following changes:
- Migrate documentation from wiki to Github, in the file `README.md`, as per https://www.jenkins.io/blog/2019/10/21/plugin-docs-on-github/
- Change plugin URL in update center to specify this README
=> Migrate documentation from Wiki

pom.xml, src/test/java/hudson/plugins/cobertura/CoberturaCoverageParserTest.java
41f9145a33a71c618760ed866995c24b04621421 long predates inclusion in JTH. See https://github.com/jenkinsci/jenkins-test-harness/commit/8dbd00774ff0d6b8276f66b8ce35167eac82a513
=> Delete explicit dep on INSANE, use MemoryAssert

src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java
[JENKINS-30647](https://issues.jenkins.io/browse/JENKINS-30647)
=> JENKINS-30647 Enable support of environment variables to define xml report pattern

.mvn/extensions.xml, Jenkinsfile, pom.xml, src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java, src/main/java/hudson/plugins/cobertura/Ratio.java, src/main/java/hudson/plugins/cobertura/targets/CoverageAggregationMode.java, src/test/java/CoverageTablePortlet/CoverageTablePortletTest.java
Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is low. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.
Includes the following pull request:
* #196
Supersedes the following pull requests:
* #213
* #211
* #209
* #207
* #193
Confirmed tests pass …
=> Test with Java 21
